module.exports = [{
  "url": "https://internproject.zendesk.com/api/v2/tickets/1.json",
  "id": 1,
  "external_id": null,
  "via": {
    "channel": "sample_ticket",
    "source": {
      "from": {},
      "to": {},
      "rel": null
    }
  },
  "created_at": "2018-02-12T21:26:11Z",
  "updated_at": "2018-02-12T21:26:11Z",
  "type": "incident",
  "subject": "Sample ticket: Meet the ticket",
  "raw_subject": "Sample ticket: Meet the ticket",
  "description": "Hi claymoresq,\n\nEmails, chats, voicemails, and tweets are captured in Zendesk Support as tickets. Start typing above to respond and click Submit to send. To test how an email becomes a ticket, send a message to support@internproject.zendesk.com.\n\nCurious about what your customers will see when you reply? Check out this video:\nhttps://demos.zendesk.com/hc/en-us/articles/202341799\n",
  "priority": "normal",
  "status": "open",
  "recipient": null,
  "requester_id": 360880420451,
  "submitter_id": 360871456331,
  "assignee_id": 360871456331,
  "organization_id": null,
  "group_id": 360000251911,
  "collaborator_ids": [],
  "follower_ids": [],
  "forum_topic_id": null,
  "problem_id": null,
  "has_incidents": false,
  "is_public": true,
  "due_at": null,
  "tags": ["sample", "support", "zendesk"],
  "custom_fields": [],
  "satisfaction_rating": null,
  "sharing_agreement_ids": [],
  "fields": [],
  "followup_ids": [],
  "brand_id": 360000157471,
  "allow_channelback": false
}, {
  "url": "https://internproject.zendesk.com/api/v2/tickets/2.json",
  "id": 2,
  "external_id": null,
  "via": {
    "channel": "api",
    "source": {
      "from": {},
      "to": {},
      "rel": null
    }
  },
  "created_at": "2018-02-12T23:18:53Z",
  "updated_at": "2018-02-12T23:18:53Z",
  "type": null,
  "subject": "velit eiusmod reprehenderit officia cupidatat",
  "raw_subject": "velit eiusmod reprehenderit officia cupidatat",
  "description": "Aute ex sunt culpa ex ea esse sint cupidatat aliqua ex consequat sit reprehenderit. Velit labore proident quis culpa ad duis adipisicing laboris voluptate velit incididunt minim consequat nulla. Laboris adipisicing reprehenderit minim tempor officia ullamco occaecat ut laborum.\n\nAliquip velit adipisicing exercitation irure aliqua qui. Commodo eu laborum cillum nostrud eu. Mollit duis qui non ea deserunt est est et officia ut excepteur Lorem pariatur deserunt.",
  "priority": null,
  "status": "open",
  "recipient": null,
  "requester_id": 360871456331,
  "submitter_id": 360871456331,
  "assignee_id": 360871456331,
  "organization_id": 360023678911,
  "group_id": 360000251911,
  "collaborator_ids": [],
  "follower_ids": [],
  "forum_topic_id": null,
  "problem_id": null,
  "has_incidents": false,
  "is_public": true,
  "due_at": null,
  "tags": ["est", "incididunt", "nisi"],
  "custom_fields": [],
  "satisfaction_rating": null,
  "sharing_agreement_ids": [],
  "fields": [],
  "followup_ids": [],
  "brand_id": 360000157471,
  "allow_channelback": false
}, {
  "url": "https://internproject.zendesk.com/api/v2/tickets/3.json",
  "id": 3,
  "external_id": null,
  "via": {
    "channel": "api",
    "source": {
      "from": {},
      "to": {},
      "rel": null
    }
  },
  "created_at": "2018-02-12T23:18:54Z",
  "updated_at": "2018-02-12T23:18:54Z",
  "type": null,
  "subject": "excepteur laborum ex occaecat Lorem",
  "raw_subject": "excepteur laborum ex occaecat Lorem",
  "description": "Exercitation amet in laborum minim. Nulla et veniam laboris dolore fugiat aliqua et sit mollit. Dolor proident nulla mollit culpa in officia pariatur officia magna eu commodo duis.\n\nAliqua reprehenderit aute qui voluptate dolor deserunt enim aute tempor ad dolor fugiat. Mollit aliquip elit aliqua eiusmod. Ex et anim non exercitation consequat elit dolore excepteur. Aliqua reprehenderit non culpa sit consequat cupidatat elit.",
  "priority": null,
  "status": "open",
  "recipient": null,
  "requester_id": 360871456331,
  "submitter_id": 360871456331,
  "assignee_id": 360871456331,
  "organization_id": 360023678911,
  "group_id": 360000251911,
  "collaborator_ids": [],
  "follower_ids": [],
  "forum_topic_id": null,
  "problem_id": null,
  "has_incidents": false,
  "is_public": true,
  "due_at": null,
  "tags": ["amet", "labore", "voluptate"],
  "custom_fields": [],
  "satisfaction_rating": null,
  "sharing_agreement_ids": [],
  "fields": [],
  "followup_ids": [],
  "brand_id": 360000157471,
  "allow_channelback": false
}];
